apiVersion: v1
kind: Service
metadata:
  name: opshell
  namespace: development
  labels:
    app: opshell
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: opshell
