---
apiVersion: v1
kind: Service
metadata:
  name: nosignal
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nosignal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nosignal
  labels:
    app: nosignal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nosignal
  template:
    metadata:
      labels:
        app: nosignal
    spec:
      containers:
      - name: nosignal
        image: opshell/nosignal:latest
        ports:
        - containerPort: 80
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: nosignal
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: nosignal
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nosignal-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - nosignal.io
    - www.nosignal.io
    secretName: nosignal-tls
  rules:
  - host: nosignal.io
    http:
      paths:
      - backend:
          serviceName: nosignal
          servicePort: 80
  - host: www.nosignal.io
    http:
      paths:
      - backend:
          serviceName: nosignal
          servicePort: 80
