---
- hosts: fleet
  remote_user: ps
  become: yes
  become_method: sudo
  roles:
    - common

- hosts: shell
  remote_user: ps
  become: yes
  become_method: sudo
  roles:
    - shell

- hosts: satellites
  remote_user: ps
  become: yes
  become_method: sudo
  roles:
    - satellite
